#!/usr/bin/env python3
"""Generate docs/RESULTS.md from the contents of results/.

The report is derived, never hand-edited, so it cannot drift from the CSVs it
describes. Rerun after any evaluation.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

RESULTS = ROOT / "results"
OUT = ROOT / "docs" / "RESULTS.md"


def ci(row: pd.Series, metric: str, nd: int = 4) -> str:
    p, lo, hi = row[metric], row[f"{metric}_lo"], row[f"{metric}_hi"]
    if pd.isna(p):
        return "n/a"
    return f"{p:.{nd}f} [{lo:.{nd}f}, {hi:.{nd}f}]"


def seg_table(df: pd.DataFrame) -> list[str]:
    lines = [
        "| Region | n | Dice [95% CI] | HD95 mm [95% CI] | Failed (Dice<0.01) | HD95 undefined |",
        "|---|---|---|---|---|---|",
    ]
    for _, r in df.iterrows():
        if r["region"] == "MEAN":
            failed = undef = ""
        else:
            failed, undef = int(r["n_failed"]), int(r["n_hd95_undefined"])
        lines.append(
            f"| {r['region']} | {r['n']} | {ci(r, 'dice')} | {ci(r, 'hd95', 2)} "
            f"| {failed} | {undef} |")
    return lines


def main() -> None:
    L: list[str] = ["# Final results", ""]
    L += ["Generated by `scripts/make_report.py` from the CSV and JSON files in",
          "`results/`. Protocol, corrections and caveats: `docs/METHODOLOGY.md`.", ""]

    # ---------------- BraTS ----------------
    L += ["## BraTS2021 segmentation", ""]
    brats_csv = RESULTS / "brats" / "segmentation_summary.csv"
    if brats_csv.exists():
        b = pd.read_csv(brats_csv)
        L += ["Internal validation, 251 cases. This partition was used for model",
              "selection during training, so it is **not** a clean test set; the",
              "clean external evaluation in this project is UPenn-GBM.", ""]
        L += seg_table(b) + [""]
    else:
        L += ["_Not available — run `scripts/summarize_brats.py`._", ""]

    # ---------------- UPenn ----------------
    L += ["## UPenn-GBM segmentation", ""]

    fixed_csv = RESULTS / "upenn" / "segmentation_summary_fixedcfg.csv"
    sens_csv = RESULTS / "upenn" / "selection_sensitivity.csv"
    if fixed_csv.exists():
        f = pd.read_csv(fixed_csv)
        fm = f[f.region == "MEAN"].sort_values("dice", ascending=False)
        L += ["Held-out test set, 29 subjects. **Primary results use a fixed",
              "configuration with no tuning**: threshold 0.5 in every region,",
              "standard component cleanup, no ET volume rule, no WT",
              "largest-component rule, identical for every setup.", "",
              "| Setup | Mean Dice [95% CI] | ET | TC | WT | Mean HD95 mm |",
              "|---|---|---|---|---|---|"]
        for _, m in fm.iterrows():
            sub = f[f.label == m["label"]]
            g = {r["region"]: r for _, r in sub.iterrows()}
            L.append(f"| `{m['label']}` | {ci(m, 'dice')} | {g['ET']['dice']:.4f} "
                     f"| {g['TC']['dice']:.4f} | {g['WT']['dice']:.4f} "
                     f"| {m['hd95']:.2f} |")
        L += [""]

        best = fm.iloc[0]
        L += [f"Best: **`{best['label']}`** at mean Dice "
              f"{ci(best, 'dice')}.", ""]
        L += seg_table(f[f.label == best["label"]]) + [""]

        if sens_csv.exists():
            c = pd.read_csv(sens_csv)
            n_better = int((c.delta_fixed_minus_selected > 0).sum())
            L += ["### Why nothing is tuned", "",
                  f"Selecting thresholds and post-processing on the 14-subject",
                  f"validation split was measured against the fixed configuration.",
                  f"Fixed wins on **{n_better} of {len(c)}** setups "
                  f"(mean {c.delta_fixed_minus_selected.mean():+.4f} Dice), so the",
                  f"selection was costing performance rather than adding it. Six",
                  f"parameters cannot be chosen on fourteen subjects.", "",
                  "| Setup | Fixed | Validation-selected | Δ |", "|---|---|---|---|"]
            for _, r in c.sort_values("fixed_dice", ascending=False).iterrows():
                L.append(f"| `{r['setup']}` | {r['fixed_dice']:.4f} | "
                         f"{r['validation_selected_dice']:.4f} | "
                         f"{r['delta_fixed_minus_selected']:+.4f} |")
            L += ["",
                  "The choice to lead with the fixed configuration rests on the",
                  "sample-size argument, not on these test numbers — picking a",
                  "selection strategy by its test performance would be test-set",
                  "tuning one level up. Both are shown so the reasoning can be",
                  "checked. See `docs/METHODOLOGY.md`.", ""]

    L += ["### Sensitivity analysis: validation-selected configuration", ""]
    upenn_csv = RESULTS / "upenn" / "segmentation_summary.csv"
    if upenn_csv.exists():
        u = pd.read_csv(upenn_csv)
        setups = list(dict.fromkeys(u["label"]))

        L += ["Held-out test set, 29 subjects. Thresholds and the ET",
              "post-processing policy were selected on the 14 validation subjects;",
              "the test set was scored once.", "",
              "### Summary across setups", "",
              "| Setup | Preproc | Mean Dice [95% CI] | ET | TC | WT | Mean HD95 mm |",
              "|---|---|---|---|---|---|---|"]
        for s in setups:
            sub = u[u.label == s]
            m = sub[sub.region == "MEAN"].iloc[0]
            g = {r["region"]: r for _, r in sub.iterrows()}
            pre = m.get("preprocessing", "")
            pre = "" if pd.isna(pre) else pre
            L.append(
                f"| `{s}` | {pre} | {ci(m, 'dice')} | {g['ET']['dice']:.4f} | "
                f"{g['TC']['dice']:.4f} | {g['WT']['dice']:.4f} | {m['hd95']:.2f} |")
        L += [""]

        for s in setups:
            sub = u[u.label == s]
            first = sub.iloc[0]
            L += [f"### `{s}`", ""]
            bits = [
                f"thresholds ET={first['et_threshold']:.2f}, "
                f"TC={first['tc_threshold']:.2f}, WT={first['wt_threshold']:.2f}",
                f"ET policy `{first['et_policy']}` "
                f"(cutoff {int(first['et_min_volume'])} voxels)",
            ]
            if "wt_policy" in first.index and pd.notna(first.get("wt_policy")):
                bits.append(f"WT policy `{first['wt_policy']}`")
            L += ["Selected on validation: " + "; ".join(bits) + ".", ""]
            if "preprocessing" in first.index and pd.notna(first.get("preprocessing")):
                L += [f"Input convention: `{first['preprocessing']}` — the one this "
                      f"checkpoint was trained under.", ""]
            L += seg_table(sub) + [""]

        da = RESULTS / "upenn" / "domain_adaptation.json"
        if da.exists():
            d = json.loads(da.read_text())
            delta, lo, hi = d["delta_mean_dice"], d["ci_low"], d["ci_high"]
            L += ["### Fine-tuning versus zero-shot transfer", "",
                  f"Fine-tuning changes mean Dice by **{delta:+.4f}** "
                  f"(95% CI [{lo:+.4f}, {hi:+.4f}], paired over the same "
                  f"{d['n_paired']} test subjects).", "",
                  "Both models are evaluated under the preprocessing they were",
                  "trained with — the BraTS checkpoint under the BraTS channel",
                  "order and min-max normalisation, the fine-tuned checkpoints",
                  "under the UPenn convention. Feeding the BraTS checkpoint the",
                  "UPenn convention, as an earlier version of this pipeline did,",
                  "understates it by roughly 0.56 Dice and inflates this",
                  "difference accordingly.", "",
                  "The interval is from a paired bootstrap, which keeps each",
                  "patient's two scores together and is the appropriate comparison",
                  "when both models are scored on the same patients.", ""]
            if lo <= 0 <= hi:
                L += ["**The interval includes zero.** With 29 test subjects this",
                      "comparison cannot establish that fine-tuning helps. Running",
                      "`scripts/crossval_upenn.py` (147 subjects) is what would",
                      "settle it.", ""]

        sel = RESULTS / "upenn" / "validation_selection.csv"
        if sel.exists():
            v = pd.read_csv(sel)
            L += ["### Post-processing selection", "",
                  "Every candidate ET policy scored on validation. The selected row",
                  "per setup is the one with the highest `val_mean_dice`.", "",
                  "| Setup | WT policy | ET policy | Cutoff | Val mean Dice | Val ET | Val WT |",
                  "|---|---|---|---|---|---|---|"]
            for s in setups:
                sub = v[v.setup == s].sort_values("val_mean_dice", ascending=False)
                for _, r in sub.iterrows():
                    L.append(
                        f"| `{s}` | {r.get('wt_policy', '')} | {r['et_policy']} | "
                        f"{int(r['et_min_volume'])} | {r['val_mean_dice']:.4f} | "
                        f"{r['val_et_dice']:.4f} | "
                        f"{r['val_wt_dice']:.4f} |" if 'val_wt_dice' in r.index else
                        f"| `{s}` | {r.get('wt_policy', '')} | {r['et_policy']} | "
                        f"{int(r['et_min_volume'])} | {r['val_mean_dice']:.4f} | "
                        f"{r['val_et_dice']:.4f} | — |")
            L += [""]
    else:
        L += ["_Not available — run `scripts/evaluate_upenn.py`._", ""]

    L += ["### Cross-validation", "",
          "Not run. `scripts/crossval_upenn.py` implements 5-fold",
          "cross-validation over all 147 expert-segmented subjects and its fold",
          "construction is verified, but training the five folds costs roughly",
          "10-14 GPU-hours and was not performed. No cross-validated number is",
          "reported here.", ""]

    # ---------------- classification ----------------
    L += ["## IDH1 classification", ""]
    idh1 = RESULTS / "classification" / "idh1_results.json"
    if idh1.exists():
        d = json.loads(idh1.read_text())
        sizes = d["cohort_sizes"]
        prev = d["prevalence_by_mask_source"]

        L += [f"Primary cohort: **{sizes['primary_n']} subjects, "
              f"{sizes['primary_positives']} IDH1-mutant** "
              f"({sizes['primary_positives'] / sizes['primary_n'] * 100:.1f}%).", "",
              "Restricted to subjects whose masks all come from the same source",
              "(model predictions). Mixing in the expert-mask subjects would",
              "reintroduce a label proxy: IDH1-mutant prevalence is",
              " vs ".join(f"{v * 100:.1f}% ({k.replace('_', ' ')})"
                          for k, v in sorted(prev.items())) + ".", "",
              "Repeated stratified 5-fold cross-validation, 10 repeats. Decision",
              "thresholds fitted on cross-fitted training-fold scores.", ""]

        for cohort_key, title in [
            ("primary_model_predicted_only", "Primary cohort — report these"),
            ("sensitivity_mixed_provenance", "Sensitivity analysis — mixed provenance"),
        ]:
            if cohort_key not in d:
                continue
            L += [f"### {title}", "",
                  "| Model | AUC [95% CI] | Balanced acc | Accuracy | Sensitivity | "
                  "Specificity | F1 |", "|---|---|---|---|---|---|---|"]
            for model, m in d[cohort_key].items():
                pb = m["auc_patient_bootstrap"]
                L.append(
                    f"| {model} | {pb['mean']:.3f} [{pb['ci_low']:.3f}, {pb['ci_high']:.3f}] "
                    f"| {m['balanced_accuracy']['mean']:.3f} "
                    f"| {m['accuracy']['mean']:.3f} "
                    f"| {m['sensitivity']['mean']:.3f} "
                    f"| {m['specificity']['mean']:.3f} "
                    f"| {m['f1']['mean']:.3f} |")
            L += [""]

        prim = d["primary_model_predicted_only"]
        best = max(prim, key=lambda k: prim[k]["auc_patient_bootstrap"]["mean"])
        bm = prim[best]
        pb = bm["auc_patient_bootstrap"]
        L += ["### Recommended model", "",
              f"**{best}**, on the primary cohort: AUC {pb['mean']:.3f} "
              f"[{pb['ci_low']:.3f}, {pb['ci_high']:.3f}], sensitivity "
              f"{bm['sensitivity']['mean']:.3f}, specificity "
              f"{bm['specificity']['mean']:.3f}.", "",
              "F1 and positive predictive value are low because prevalence is",
              "about 4%: at that base rate most positive calls are false even",
              "with good discrimination. AUC and the sensitivity/specificity pair",
              "describe this model better than F1 does.", "",
              f"With {sizes['primary_positives']} positive cases this is a",
              "feasibility result, not a validated classifier. The confidence",
              "intervals are the result; the point estimates should not be quoted",
              "alone.", ""]
    else:
        L += ["_Not available — run `scripts/train_classifier_idh1.py`._", ""]

    L += ["## MGMT classification", "",
          "Not retained. The earlier MGMT experiment (n=116, accuracy 0.62,",
          "AUC 0.65) was run on a different cohort with a pipeline that no longer",
          "exists in this repository, and its per-case outputs could not be tied",
          "to a reproducible split. Rather than report a number that cannot be",
          "regenerated, it has been archived. `brats_gbm/data/upenn.py` still",
          "supports `target_label=\"MGMT\"`, so the analysis can be redone",
          "properly against the current pipeline.", ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
